// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaiycolzcwuvmedmlkwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhaXljb2x6Y3d1dm1lZG1sa3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDE1NDIsImV4cCI6MjA2NDE3NzU0Mn0.apfiz1f_3qHvB_o92V9gNi__zV_feCo6tNMheP9MWC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);